// cells
export const GENERATE_CELLS = 'GENERATE_CELLS'
export const GENERATE_CELLS_SUCCEEDED = 'GENERATE_CELLS_SUCCEEDED'
export const GENERATE_CELLS_FAILED = 'GENERATE_CELLS_FAILED'
export const UPDATE_SELECTED_CELL_ID = 'UPDATE_SELECTED_CELL_ID'
export const MARK_CELL_COMPLETED = 'MARK_CELL_COMPLETED'
export const ADD_PENCIL_MARK = 'ADD_PENCIL_MARK'
export const REMOVE_PENCIL_MARK = 'REMOVE_PENCIL_MARK'

// fault
export const UPDATE_FAULT_CELL_ID = 'UPDATE_FAULT_CELL_ID'
export const INCREMENT_FAULT_COUNTER = 'INCREMENT_FAULT_COUNTER'

// control bar
export const SET_CURRENT_MARKER = 'SET_CURRENT_MARKER'

// puzzle
export const PUZZLE_TOGGLE_COMPLETED = 'PUZZLE_TOGGLE_COMPLETED'
