export const UPDATE_SELECTED_CELL = 'UPDATE_SELECTED_CELL'
export const UPDATE_PUZZLE_CELL = 'UPDATE_PUZZLE_CELL'
export const SET_FAULT_CELL = 'SET_FAULT_CELL'
export const INCREMENT_FAULT_COUNTER = 'INCREMENT_FAULT_COUNTER'
