// grid
export const UPDATE_SELECTED_CELL_ID = 'UPDATE_SELECTED_CELL_ID'
export const MARK_CELL_COMPLETED = 'MARK_CELL_COMPLETED'
export const ADD_PENCIL_MARK = 'ADD_PENCIL_MARK'
export const REMOVE_PENCIL_MARK = 'REMOVE_PENCIL_MARK'

//fault
export const SET_FAULT_CELL = 'SET_FAULT_CELL'
export const INCREMENT_FAULT_COUNTER = 'INCREMENT_FAULT_COUNTER'

//control bar
export const SET_CURRENT_MARKER = 'SET_CURRENT_MARKER'
